// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5nZpCzj8LBjeIeaxLnI7wqNNVV7qvMYY',
    appId: '1:661589244767:web:cf87aef22b6e830ee414ea',
    messagingSenderId: '661589244767',
    projectId: 'app1-81df0',
    authDomain: 'app1-81df0.firebaseapp.com',
    storageBucket: 'app1-81df0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4xukZB8Ou1c0kp0Ec39Yw3gNDVj30yrQ',
    appId: '1:661589244767:android:301c272261844826e414ea',
    messagingSenderId: '661589244767',
    projectId: 'app1-81df0',
    storageBucket: 'app1-81df0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZw3ilzzwMfzWLdhaT-C9MgxVUPOYAjQ',
    appId: '1:661589244767:ios:b407331d1cddc54ae414ea',
    messagingSenderId: '661589244767',
    projectId: 'app1-81df0',
    storageBucket: 'app1-81df0.appspot.com',
    iosClientId: '661589244767-nmf5sff22o4el94aaqa44mb2aic1ijov.apps.googleusercontent.com',
    iosBundleId: 'com.example.appp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZw3ilzzwMfzWLdhaT-C9MgxVUPOYAjQ',
    appId: '1:661589244767:ios:31a9bf32b69f78a3e414ea',
    messagingSenderId: '661589244767',
    projectId: 'app1-81df0',
    storageBucket: 'app1-81df0.appspot.com',
    iosClientId: '661589244767-cdh73kubs0aiqjsnrdotb8u73q8e1pqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.appp.RunnerTests',
  );
}
